### ISSUE TITLE
1.9.2 

### ISSUE THREAD

**Issue by Kevinco1** [re-zero001/LSPosed-PrivateArchive#1]
What advantages does 1.9.2 offer that a newer version of LSposed doesn't?

**Comment by re-zero001** [comment]
I like 1.9.2

**Comment by re-zero001** [comment]
You can view the changelog.
In other words, I made more bug fixes.

**Comment by Kevinco1** [comment]
Bug fixes for existing 1.9.2 I know, but just wondering why you went with older version of LSposed

**Comment by re-zero001** [comment]
> Bug fixes for existing 1.9.2 I know, but just wondering why you went with older version of LSposed

I like 1.9.2

**Comment by Kevinco1** [comment]
> > Bug fixes for existing 1.9.2 I know, but just wondering why you went with older version of LSposed
> 
> I like 1.9.2

Cool, just didn't know if 1.9.2 had better hiding capabilities or something else to go with that instead of newer version

**Comment by re-zero001** [comment]
I told you to look at the changelog, and I'm annoyed that you're asking me this.
I don't like to say bad things directly, this is a warning.
