### ISSUE TITLE
Lspatch

### ISSUE THREAD

**Issue by erevos13** [re-zero001/LSPosed-PrivateArchive#2]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Any updates on this core based lspatch ?

### Describe the solution you'd like/描述你想要的解决方案

Maybe lspatch based on this lsposed fork fixes the issues with other lspatch forks ?

**Comment by re-zero001** [comment]
Due to the serious trafficking, I will not consider updating LSPatch.
Officials will no longer update LSPatch too.
Actually the main reason is: I don't need LSPatch.
