### ISSUE TITLE
什么时候更新lspatch😭

### ISSUE THREAD

**Issue by VanemKrAu** [re-zero001/LSPosed-PrivateArchive#5]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

在安卓15上无法正常使用lspatch内置软件
![Screenshot_2024-11-02-09-54-21-560_com miui thirdappassistant-edit](https://github.com/user-attachments/assets/58479841-56a4-4324-a9bf-26a260611034)

### Describe the solution you'd like/描述你想要的解决方案

希望可以更新lspatch到安卓15可用版本，这对我这种未root用户真的很重要😭😭😭

**Comment by re-zero001** [comment]
#2

**Comment by VanemKrAu** [comment]
不会更新吗😭
